project_id = "svierarfcolhcfjpmwck"

[functions.create-player]
verify_jwt = false

[functions.bulk-import]
verify_jwt = false

[functions.clear-test-data]
verify_jwt = false

[functions.save-pending-signup]
verify_jwt = false
